QLBanDongHo60135761/Controllers/DongHoes_60135761Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLBanDongHo60135761.Models;

namespace QLBanDongHo60135761.Controllers
{
    public class DongHoes_60135761Controller : Controller
    {
        private QLDHC_ThienPhatEntities db = new QLDHC_ThienPhatEntities();

        // GET: DongHoes_60135761
        public ActionResult Index()
        {
            var dongHoes = db.DongHoes.Include(d => d.LoaiDongHo).Include(d => d.NhaCungCap);
            if (Session["idAdmin"] == null || Session["idAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Clients_60135761");
            }
            else
                return View(dongHoes.ToList());
        }

        // GET: DongHoes_60135761/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // GET: DongHoes_60135761/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiDH = new SelectList(db.LoaiDongHoes, "MaLoaiDH", "TenLoaiDH");
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC");
            return View();
        }

        // POST: DongHoes_60135761/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,TenDongHo,AnhSanPham,GiaBan,Mota,GhiChu,MaLoaiDH,MaNCC")] DongHo dongHo)
        {
            var imgDH = Request.Files["Avatar"];

            string postedFileName = System.IO.Path.GetFileName(imgDH.FileName);

            var path = Server.MapPath("/Images/" + postedFileName);
            imgDH.SaveAs(path);

            if (ModelState.IsValid)
            {
                dongHo.AnhSanPham = postedFileName;
                db.DongHoes.Add(dongHo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiDH = new SelectList(db.LoaiDongHoes, "MaLoaiDH", "TenLoaiDH", dongHo.MaLoaiDH);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", dongHo.MaNCC);
            return View(dongHo);
        }

        // GET: DongHoes_60135761/Edit/5
        public ActionResult Edit(string id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiDH = new SelectList(db.LoaiDongHoes, "MaLoaiDH", "TenLoaiDH", dongHo.MaLoaiDH);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", dongHo.MaNCC);
            return View(dongHo);
        }

        // POST: DongHoes_60135761/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,TenDongHo,AnhSanPham,GiaBan,Mota,GhiChu,MaLoaiDH,MaNCC")] DongHo dongHo)
        {
            var imgDH = Request.Files["Avatar"];
            try
            {
                string postedFileName = System.IO.Path.GetFileName(imgDH.FileName);
                var path = Server.MapPath("/Images/" + postedFileName);
                imgDH.SaveAs(path);
            }
            catch
            { }
            if (ModelState.IsValid)
            {
                db.Entry(dongHo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiDH = new SelectList(db.LoaiDongHoes, "MaLoaiDH", "TenLoaiDH", dongHo.MaLoaiDH);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", dongHo.MaNCC);
            return View(dongHo);
        }

        // GET: DongHoes_60135761/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: DongHoes_60135761/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DongHo dongHo = db.DongHoes.Find(id);
            db.DongHoes.Remove(dongHo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TimKiem_60135761(string maDH = "", string tenDH = "", string giaMin = "", string giaMax = "", string maloaiDH = "", string maNCC = "")
        {
            string min = giaMin, max = giaMax;
            ViewBag.maDH = maDH;
            ViewBag.tenDH = tenDH;
            if (giaMin == "")
            {
                ViewBag.giaMin = "";
                min = "0";
            }
            else
            {
                ViewBag.giaMin = giaMin;
                min = giaMin;
            }
            if (max == "")
            {
                max = Int32.MaxValue.ToString();
                ViewBag.giaMax = "";// Int32.MaxValue.ToString(); 
            }
            else
            {
                ViewBag.giaMax = giaMax;
                max = giaMax;
            }
            ViewBag.MaLoaiDH = new SelectList(db.LoaiDongHoes, "MaLoaiDH", "TenLoaiDH");
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC");
            var dongHoes = db.DongHoes.SqlQuery("DongHo_TimKiem'" + maDH + "',N'" + tenDH + "','" + min + "','" + max + "','" + maloaiDH + "','" + maNCC + "'");
            if (dongHoes.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(dongHoes.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLBanDongHo60135761/Views/DongHoes_60135761/Create.cshtml
@model QLBanDongHo60135761.Models.DongHo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>THÔNG TIN ĐỒNG HỒ</h2>


@using (Html.BeginForm("Create", "DongHoes_60135761", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaDH, "Mã đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDongHo, "Tên đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDongHo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSanPham, "Ảnh sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, "Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiDH, "Loại đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiDH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" style="width: 120px;" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary",@style="width: 120px;" })
</div>

QLBanDongHo60135761/Views/DongHoes_60135761/Delete.cshtml
@model QLBanDongHo60135761.Models.DongHo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
}

<h3 style="color: red;">Bạn có chắc chắn xoá thông tin này?</h3>
<table border="0" cellpadding="0" cellspacing="0" style="font-size:16px;margin-left:50px;">
    <tr>
        <td>
            <table cellpadding="2" cellspacing="10">
                <caption class="text-center"><b>THÔNG TIN CHI TIẾT</b></caption>
                <tr>
                    <td rowspan="8"><img src="/Images/@Html.DisplayFor(model => model.AnhSanPham)" width="200" height="200" /></td>
                    <th>Mã đồng hồ: </th>
                    <td>@Html.DisplayFor(model => model.MaDH)</td>
                </tr>
                <tr>
                    <th>Tên đồng hồ: </th>
                    <td>@Html.DisplayFor(model => model.TenDongHo)</td>
                </tr>
                <tr>
                    <th>Giá bán: </th>
                    <td>@Html.DisplayFor(model => model.GiaBan)</td>
                </tr>
                <tr>
                    <th>Mô tả: </th>
                    <td>
                        @Html.DisplayFor(model => model.Mota)
                    </td>
                </tr>
                <tr>
                    <th>Ghi chú: </th>
                    <td>@Html.DisplayFor(model => model.GhiChu)</td>
                </tr>
                <tr>
                    <th>Loại Đồng Hồ: </th>
                    <td>@Html.DisplayFor(model => model.LoaiDongHo.TenLoaiDH)</td>
                </tr>
                <tr>
                    <th>Nhà cung cấp: </th>
                    <td>@Html.DisplayFor(model => model.NhaCungCap.TenNCC)</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="margin-left:100px; margin-top: 10px;">
        <input type="submit" value="Xóa" class="btn btn-danger" style="width: 120px;" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary",@style="width: 120px;" })
    </div>
}

QLBanDongHo60135761/Views/DongHoes_60135761/Details.cshtml
@model QLBanDongHo60135761.Models.DongHo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
   
}

<table border="0" cellpadding="0" cellspacing="0" style="font-size:16px;margin-left:50px;">
    <tr>
        <td>
            <table cellpadding="2" cellspacing="10">
                <caption class="text-center" style="font-size: 20px;"><b>THÔNG TIN CHI TIẾT</b></caption>
                <tr>
                    <td rowspan="32"><img src="/Images/@Html.DisplayFor(model => model.AnhSanPham)" width="200" height="200" /></td>
                    <th>Mã đồng hồ: </th>
                    <td>@Html.DisplayFor(model => model.MaDH)</td>
                </tr>
                <tr>
                    <th>Tên đồng hồ: </th>
                    <td>@Html.DisplayFor(model => model.TenDongHo)</td>
                </tr>
                <tr>
                    <th>Giá bán: </th>
                    <td>@Html.DisplayFor(model => model.GiaBan)</td>
                </tr>
                <tr>
                    <th>Mô tả: </th>
                    <td>
                        @Html.DisplayFor(model => model.Mota)
                    </td>
                </tr>
                <tr>
                    <th>Ghi chú: </th>
                    <td>@Html.DisplayFor(model => model.GhiChu)</td>
                </tr>
                <tr>
                    <th>Loại Đồng Hồ: </th>
                    <td>@Html.DisplayFor(model => model.LoaiDongHo.TenLoaiDH)</td>
                </tr>
                <tr>
                    <th>Nhà cung cấp: </th>
                    <td>@Html.DisplayFor(model => model.NhaCungCap.TenNCC)</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<p style="margin-left:100px;margin-top: 20px;">
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MaDH }, new { @class = "btn btn-success" })
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
</p>

QLBanDongHo60135761/Views/DongHoes_60135761/Edit.cshtml
@model QLBanDongHo60135761.Models.DongHo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var fileupload = $("#Avatar");
            var image = $("#FileUpload");
            image.click(function () {
                fileupload.click();
            });
            fileupload.change(function () {
                var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                document.getElementById("AnhSanPham").value = fileName;
            });
        });
    </script>
   
}

<h2>CẬP NHẬT THÔNG TIN ĐỒNG HỒ</h2>


@using (Html.BeginForm("Edit", "DongHoes_60135761", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDH)

        <div class="form-group">
            @Html.LabelFor(model => model.MaDH, "Mã đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDongHo, "Tên đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDongHo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDongHo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSanPham, "Ảnh sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSanPham, "", new { @class = "text-danger" })
                <input type="file" name="Avatar" id="Avatar" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, "Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiDH, "Loại đồng hồ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiDH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
</div>

QLBanDongHo60135761/Views/DongHoes_60135761/Index.cshtml
@model IEnumerable<QLBanDongHo60135761.Models.DongHo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenDongHo", rowsPerPage: 5);
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="#" rel="stylesheet" />
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                  
                }

        #gridContent img {
            cursor: pointer;
        }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <h2>DANH SÁCH ĐỒNG HỒ</h2>
    <p>
        @Html.ActionLink("Tạo mới", "Create", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Tìm kiếm", "TimKiem_60135761", null, new { @class = "btn btn-info" })
    </p>
    <div id="gridContent" style="font-size: 16px;">

        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]
            {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                grid.Column("MaDH","Mã đồng hồ"),
                grid.Column("TenDongHo","Tên đồng hồ"),
                grid.Column("AnhSanPham","Ảnh sản phẩm"),
                grid.Column("GiaBan","Gía bán",format:@<text> @item.GiaBan.ToString("#,##0 đồng")</text>),
                grid.Column("Mota","Mô tả"),
                grid.Column("LoaiDongHo.TenLoaiDH","Loại đồng hồ"),
                grid.Column("NhaCungCap.TenNCC","Nhà cung cấp"),
                grid.Column("GhiChu","Ghi chú"),
                grid.Column("Chức năng",format:@<text>
                    <a href="@Url.Action("Edit", new {id = item.MaDH})"><abbr title="Cập nhật dữ liệu"><img width="20" height="20" src="~/Images/edit.png" /></abbr></a>
                    <a href="@Url.Action("Details", new {id = item.MaDH})"><abbr title="Chi tiết"><img width="20" height="20" src="~/Images/details.png" /></abbr></a>
                    <a href="@Url.Action("Delete", new {id = item.MaDH})"><abbr title="Xoá"><img width="20" height="20" src="~/Images/delete.png" /></abbr></a>
</text>)
}
)
    </div>
</body>
</html>

QLBanDongHo60135761/Views/DongHoes_60135761/TimKiem_60135761.cshtml
@{
    ViewBag.Title = "TimKiem_60135761";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenDongHo", rowsPerPage: 5);
   
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="#" rel="stylesheet" />
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        #gridContent img {
            cursor: pointer;
        }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
                  
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("TimKiem_60135761", "DongHoes_60135761", FormMethod.Get))
        {
            @Html.AntiForgeryToken()


        <table class="table1" align="center">
            <tr>
                <td>
                    <div> Mã đồng hồ</div>
                </td>
                <td>
                    <input type="text" name="maDH" value="@ViewBag.maDH" />
                </td>

            </tr>
            <tr>
                <td>Tên đồng hồ</td>
                <td>
                    <input type="text" name="tenDH" value="@ViewBag.tenDH" />
                </td>

            </tr>


            <tr>
                <td>Giá từ</td>
                <td>
                    <input type="text" name="giaMin" value="@ViewBag.giaMin" />
                    Đến<input type="text" name="giaMax" value="@ViewBag.giaMax" />
                </td>

            </tr>
            <tr>
                <td>Loại đồng hồ</td>
                <td>
                    @Html.DropDownList("MaLoaiDH", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td>Nhà cung cấp</td>
                <td>
                    @Html.DropDownList("MaNCC", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:120px;
                background-color: blue;color:white" />
                    <input type="button" name="Nhapmoi" value="Làm mới" style="margin-left: 5px;width:120px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiem_60135761", "DongHoes_60135761/TimKiem_60135761")'" />

                </td>
            </tr>
        </table>
        }
    </div>
    <div id="gridContent">
        <p style="color: red;"> @ViewBag.TB</p>
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]
            {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                grid.Column("MaDH","Mã đồng hồ"),
                grid.Column("TenDongHo","Tên đồng hồ"),
                grid.Column("AnhSanPham","Ảnh sản phẩm"),
                grid.Column("GiaBan","Gía bán",format:@<text> @item.GiaBan.ToString("#,##0 đồng")</text>),
                grid.Column("Mota","Mô tả"),
                grid.Column("LoaiDongHo.TenLoaiDH","Loại đồng hồ"),
                grid.Column("NhaCungCap.TenNCC","Nhà cung cấp"),
                grid.Column("GhiChu","Ghi chú"),
                grid.Column("Chức năng",format:@<text>
                    <a href="@Url.Action("Edit", new {id = item.MaDH})"><abbr title="Cập nhật dữ liệu"><img width="20" height="20" src="~/Images/edit.png" /></abbr></a>
                    <a href="@Url.Action("Details", new {id = item.MaDH})"><abbr title="Chi tiết"><img width="20" height="20" src="~/Images/details.png" /></abbr></a>
                    <a href="@Url.Action("Delete", new {id = item.MaDH})"><abbr title="Xoá"><img width="20" height="20" src="~/Images/delete.png" /></abbr></a>
</text>)
}
)
    </div>
</body>
</html>