QLBanDongHo60135761/Controllers/Clients_60135761Controller.cs
using QLBanDongHo60135761.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLBanDongHo60135761.Controllers
{
    public class Clients_60135761Controller : Controller
    {
        QLDHC_ThienPhatEntities _db = new QLDHC_ThienPhatEntities();
        // GET: Clients_60135761
        public ActionResult TrangChu()
        {
            return View(_db.DongHoes.ToList());
        }
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangNhap(string email, string password)
        {
            if (ModelState.IsValid)
            {

                var data = _db.QuanTriViens.Where(s => s.Email.Equals(email) && s.Password.Equals(password)).ToList();
                if (data.Count() > 0)
                {
                    Session["idAdmin"] = data.FirstOrDefault().IdAdmin;
                    return RedirectToAction("../DongHoes_60135761/Index");
                }
                else
                {
                    ViewBag.error = "Đăng nhập không thành công! Vui lòng đăng nhập lại.";
                    return View("../Clients_60135761/DangNhap");
                }
            }
            return View();
        }

        public ActionResult ThanhCong()
        {
            return View();
        }
    }
}

QLBanDongHo60135761/Views/Clients_60135761/DangNhap.cshtml
@model QLBanDongHo60135761.Models.QuanTriVien
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2>THÔNG TIN ĐĂNG NHẬP</h2>
            </div>

            <div class="card-body" style="font-size: 16px;">
                @using (Html.BeginForm("DangNhap", "Clients_60135761", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Đăng nhập" style="width: 120px;" />
                    </div>

                }

            </div>

        </div>
    </div>
    <p style="color: red; width: 80%; display:inline-block; font-size: 16px;">@ViewBag.error</p>
</div>

QLBanDongHo60135761/Views/Clients_60135761/ThanhCong.cshtml
@{
    ViewBag.Title = "ThanhCong";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        #success {
            width: 500px;
            height: 300px;
            margin: 0 auto;
            text-align: center;
            padding: 20px;
        }

        img {
            padding-top: 10px;
            width: 180px;
            height: 180px;
            background-color: white;
        }

        h2 {
            margin-bottom: 0;
        }

        p {
            font-size: 22px;
        }
    </style>
</head>


<div id="success">
    <img src="~/Images/success.png" alt="" />
    <h2>Chúc mừng</h2>
    <p>
        Bạn đã đăng ký thành công !
    </p>
</div>

QLBanDongHo60135761/Views/Clients_60135761/TrangChu.cshtml
@model IEnumerable<QLBanDongHo60135761.Models.DongHo>
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}


<head>
    <style>
        .cart {
            width: 260px;
            height: 325px;
            border-radius: 5px;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }

            .cart:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }

        img {
            cursor: pointer;
        }

        #margin-cart {
            text-align: center;
            margin-top: 20px;
        }

            #margin-cart span {
                display: block;
                margin-top: 20px;
                padding-top: 5px;
                font-size: 18px;
                color: #0026ff;
                font-weight: bold;
            }

            #search-box {
                width: 50%;
                height: 50px;
                
                padding: 10px 7px;
                font-size: 18px;
                border-radius: 5px;
                border: 1px solid gray;
                margin: 10px auto;
            }
            #search-box input {
               width: 90%;
                outline: none;
                border: none;                

            }

        .buy {
            margin-top: 2px;
            display: inline-block;
            width: 100%;
            max-width: 120px;
            height: 24px;
            background-color: white;
            border: 1px solid gray;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            color: #696969;
            
        }
        .cart p {
            height: 22px;
            font-size: 16px;
            overflow: hidden;
            display: inline-block;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 1;
        }


            .buy:hover {
                background-color: #00008B;
                color: white;
                text-decoration: none;
            }
    </style>
</head>
<div>
    <div id="search-box">
        <input type="text" name="search-bar" value="" placeholder="Tìm kiếm" />        
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-6 col-md-4 col-lg-3" id="margin-cart">
                <div class="cart">
                    <p style="margin-bottom: 0;"><b>@Html.DisplayFor(model => item.TenDongHo)</b></p>
                    <div style="height: 200px; width: 200px;">
                        <img src="~/Images/@Url.Content(item.AnhSanPham)" style="height: 100%; width: 100%; margin: 10px;" />
                    </div>
                    <span>Giá: @Html.DisplayFor(model => item.GiaBan) <br />
                           <a href="#" class="buy">Mua</a>
                    </span>
                    
                </div>
            </div>
        }
    </div>
</div>